import { Link } from "wouter";
import logo from "@assets/newstemcelllogo_1757155983144.png";
import footerLogo from "@assets/stemlog-white_1756400363335.png";

export default function MedicalDisclaimer() {
  return (
    <>
      {/* SEO Head Elements */}
      <title>Medical Disclaimer - FreeStemCellReport.com</title>
      <meta name="description" content="Medical disclaimer for FreeStemCellReport.com clarifying that our content is educational only and not a substitute for professional medical advice." />
      <link rel="canonical" href="https://www.freestemcellreport.com/medical-disclaimer" />
      
      <div className="min-h-screen" style={{ backgroundColor: '#e4e2dd' }}>
        {/* Header */}
        <header className="shadow-sm" style={{ backgroundColor: 'rgba(255, 255, 255, 0.9)' }}>
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center py-4">
              <Link href="/">
                <img 
                  src={logo} 
                  alt="FreeStemCellReport.com" 
                  className="max-w-[225px] h-auto cursor-pointer"
                />
              </Link>
              
              <nav className="hidden md:flex space-x-8">
                <Link href="/" className="text-gray-700 hover:text-medical-blue transition-colors font-medium">Home</Link>
                <Link href="/about-doctor" className="text-gray-700 hover:text-medical-blue transition-colors font-medium">Dr. McCarthy</Link>
                <Link href="/stem-cells-colombia" className="text-gray-700 hover:text-medical-blue transition-colors font-medium">Stem Cells Colombia</Link>
                <span className="text-medical-blue font-medium">Medical Disclaimer</span>
              </nav>
            </div>
          </div>
        </header>

        {/* Breadcrumbs */}
        <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4" aria-label="Breadcrumb">
          <ol className="flex items-center space-x-2 text-sm text-gray-500">
            <li><Link href="/" className="hover:text-medical-blue">Home</Link></li>
            <li>/</li>
            <li className="text-gray-900">Medical Disclaimer</li>
          </ol>
        </nav>

        {/* Main Content */}
        <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8">
            <h1 className="text-4xl font-title-medium text-gray-900 mb-6">Medical Disclaimer</h1>
            <p className="text-sm text-gray-500 mb-8">Last updated: {new Date().toLocaleDateString()}</p>

            <div className="prose prose-lg max-w-none">
              
              {/* Important Notice */}
              <div className="bg-red-50 border-l-4 border-red-400 p-6 mb-8">
                <h2 className="text-xl font-bold text-red-800 mb-3">⚠️ IMPORTANT MEDICAL NOTICE</h2>
                <p className="text-red-700 font-medium">
                  This website provides educational information only and is NOT a substitute for professional medical advice, diagnosis, or treatment. Always consult with qualified healthcare professionals before making any medical decisions.
                </p>
              </div>

              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">No Medical Advice</h2>
              <p className="text-gray-700 mb-4">
                FreeStemCellReport.com and its content creators, including Dr. Daisy McCarthy, MD, do not provide medical advice, diagnosis, or treatment through this website. All information is provided for general educational and informational purposes only.
              </p>
              <p className="text-gray-700 mb-6">
                The personalized reports generated by our assessment tools are educational resources designed to help you understand stem cell therapy options and formulate better questions for your healthcare provider. They are not medical recommendations or treatment plans.
              </p>

              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Educational Purpose Only</h2>
              <p className="text-gray-700 mb-4">All content on this website, including but not limited to:</p>
              <ul className="list-disc list-inside text-gray-700 mb-6 space-y-2">
                <li>Assessment questionnaires and personalized reports</li>
                <li>Educational articles and blog posts</li>
                <li>Information about stem cell therapy and regenerative medicine</li>
                <li>Voice chat interactions and AI-generated responses</li>
                <li>Video content and educational materials</li>
                <li>Treatment option descriptions and success rate information</li>
              </ul>
              <p className="text-gray-700 mb-6">
                Is provided solely for educational purposes to help individuals better understand stem cell therapy and make more informed discussions with their healthcare providers.
              </p>

              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">No Doctor-Patient Relationship</h2>
              <p className="text-gray-700 mb-6">
                Using this website, completing assessments, or scheduling consultations does not create a doctor-patient relationship between you and Dr. Daisy McCarthy, MD, or any other healthcare professional associated with FreeStemCellReport.com. Any consultations offered are educational discussions only.
              </p>

              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Consult Your Healthcare Provider</h2>
              <div className="bg-blue-50 border-l-4 border-blue-400 p-6 mb-6">
                <p className="text-blue-800 font-medium">
                  <strong>Always consult with your physician or other qualified healthcare provider before:</strong>
                </p>
                <ul className="list-disc list-inside text-blue-700 mt-3 space-y-2">
                  <li>Making any decisions about medical treatment</li>
                  <li>Starting, stopping, or changing any medication or treatment regimen</li>
                  <li>Pursuing stem cell therapy or regenerative medicine treatments</li>
                  <li>Traveling for medical treatment (medical tourism)</li>
                  <li>Making lifestyle changes based on information from this website</li>
                </ul>
              </div>

              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Individual Results May Vary</h2>
              <p className="text-gray-700 mb-6">
                Any success rates, timelines, or outcome information presented on this website represents general research findings and educational information. Individual results may vary significantly. Your specific medical condition, health status, treatment response, and outcomes cannot be predicted based on general information.
              </p>

              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">FDA and Regulatory Status</h2>
              <p className="text-gray-700 mb-4">
                Many stem cell treatments discussed on this website are not approved by the FDA and are considered experimental. Information about treatments available in other countries, including Colombia, may not reflect treatments available or approved in your jurisdiction.
              </p>
              <p className="text-gray-700 mb-6">
                Always verify the regulatory status and legal availability of any treatment you are considering in your specific location.
              </p>

              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Emergency Medical Situations</h2>
              <div className="bg-red-50 border-l-4 border-red-400 p-6 mb-6">
                <p className="text-red-800 font-bold">
                  🚨 If you are experiencing a medical emergency, call your local emergency number (911 in the US) immediately. Do not rely on information from this website for emergency medical situations.
                </p>
              </div>

              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Third-Party Information</h2>
              <p className="text-gray-700 mb-6">
                This website may contain links to third-party websites, research studies, or other external sources. We do not control or endorse the content of external websites and are not responsible for their accuracy, completeness, or medical advice provided by third parties.
              </p>

              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Artificial Intelligence Limitations</h2>
              <p className="text-gray-700 mb-6">
                Our website uses AI technology to generate personalized educational content and provide interactive chat features. AI responses are based on general information and algorithms, not individual medical assessment. AI-generated content should never be considered medical advice and may contain errors or limitations.
              </p>

              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Medical Tourism Considerations</h2>
              <p className="text-gray-700 mb-4">
                If you are considering medical treatment abroad, including in Colombia or other destinations:
              </p>
              <ul className="list-disc list-inside text-gray-700 mb-6 space-y-2">
                <li>Consult with your local healthcare provider before traveling</li>
                <li>Research the credentials and accreditation of foreign medical facilities</li>
                <li>Understand potential risks, including complications, follow-up care limitations, and legal recourse</li>
                <li>Verify insurance coverage for treatments and complications abroad</li>
                <li>Consider language barriers and communication challenges</li>
              </ul>

              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Accuracy of Information</h2>
              <p className="text-gray-700 mb-6">
                While we strive to provide accurate and up-to-date information, medical knowledge and treatment options evolve rapidly. We cannot guarantee the completeness, accuracy, or timeliness of all information presented. Always verify information with current medical literature and qualified healthcare professionals.
              </p>

              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Liability Limitation</h2>
              <p className="text-gray-700 mb-6">
                FreeStemCellReport.com, its creators, contributors, and affiliated healthcare professionals disclaim any liability for decisions made based on information provided on this website. Users assume full responsibility for their healthcare decisions and any consequences thereof.
              </p>

              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Updates to This Disclaimer</h2>
              <p className="text-gray-700 mb-6">
                This medical disclaimer may be updated periodically to reflect changes in our services or regulatory requirements. The "Last updated" date at the top of this page indicates when the most recent changes were made.
              </p>

              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Contact Information</h2>
              <p className="text-gray-700 mb-4">
                If you have questions about this medical disclaimer:
              </p>
              <div className="bg-gray-50 p-4 rounded-lg">
                <p className="text-gray-700">
                  <strong>Email:</strong> medical@freestemcellreport.com<br/>
                  <strong>Address:</strong> FreeStemCellReport.com Medical Team<br/>
                  Educational Content Division<br/>
                  United States
                </p>
              </div>

              <div className="bg-yellow-50 border-l-4 border-yellow-400 p-6 mt-8">
                <p className="text-yellow-800 font-medium">
                  <strong>Remember:</strong> Your health is important. When in doubt, always consult with qualified healthcare professionals who can evaluate your individual situation and provide personalized medical guidance.
                </p>
              </div>
            </div>
          </div>
        </main>

        {/* Footer */}
        <footer className="bg-gray-900 text-white py-12 mt-16">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="grid md:grid-cols-4 gap-8">
              <div>
                <div className="mb-4">
                  <img 
                    src={footerLogo} 
                    alt="FreeStemCellReport.com" 
                    className="h-16 w-auto"
                  />
                </div>
                <p className="text-gray-300 text-sm">
                  Educational information about stem cell therapy options and regenerative medicine.
                </p>
              </div>
              
              <div>
                <h4 className="font-semibold mb-4">Quick Links</h4>
                <ul className="space-y-2 text-sm text-gray-300">
                  <li><Link href="/" className="hover:text-white transition-colors">Free Assessment</Link></li>
                  <li><Link href="/about-doctor" className="hover:text-white transition-colors">About Dr. McCarthy</Link></li>
                  <li><Link href="/stem-cells-colombia" className="hover:text-white transition-colors">Stem Cells Colombia</Link></li>
                </ul>
              </div>
              
              <div>
                <h4 className="font-semibold mb-4">Learn More</h4>
                <ul className="space-y-2 text-sm text-gray-300">
                  <li><Link href="/" className="hover:text-white transition-colors">FAQ</Link></li>
                  <li><a href="https://calendly.com/bennvb12/new-meeting" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-colors">Book Consultation</a></li>
                </ul>
              </div>
              
              <div>
                <h4 className="font-semibold mb-4">Legal</h4>
                <ul className="space-y-2 text-sm text-gray-300">
                  <li><Link href="/privacy-policy" className="hover:text-white transition-colors">Privacy Policy</Link></li>
                  <li><Link href="/terms-of-service" className="hover:text-white transition-colors">Terms of Service</Link></li>
                  <li><span className="text-white">Medical Disclaimer</span></li>
                  <li><Link href="/cookie-policy" className="hover:text-white transition-colors">Cookie Policy</Link></li>
                </ul>
              </div>
            </div>
            
            <div className="mt-8 pt-8 border-t border-gray-800 text-center text-gray-400 text-sm">
              <p>&copy; {new Date().getFullYear()} FreeStemCellReport.com. All rights reserved.</p>
              <p className="mt-2">This platform provides educational information only and is not intended as medical advice.</p>
            </div>
          </div>
        </footer>
      </div>
    </>
  );
}